apiVersion: v1
kind: Service
metadata:
  name: vote-lb
  namespace: vote
  ## Anotacion que permite decirle a la nube que el balanceador tenga acceso por internet
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: votedeployment
  ports:
  - port: 5001
    protocol: TCP    
    targetPort: 80
    name: http-2