apiVersion: v1
kind: Service
metadata:
  name: result-lb
  namespace: vote
  ## Anotacion que permite decirle a la nube que el balanceador tenga acceso por internet
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: resultdeployment
  ports:
  - port: 5002
    protocol: TCP    
    targetPort: 80
    name: http-3