apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  ## Anotacion que permite decirle a la nube que el balanceador tenga acceso por internet
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: ClusterIP
  selector:
    app: db-deployment

  ports:
  - port: 5432
    #protocol: TCP
    targetPort: 5432
    name: http-1
